# Generated by Django 5.2.5 on 2025-08-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.CharField(default='666', max_length=100)),
                ('lattitude', models.FloatField(default=51.0)),
                ('longitude', models.FloatField(default=1.65)),
                ('speed', models.FloatField(default=0.0)),
            ],
        ),
    ]
