# Generated by Django 5.2.5 on 2025-08-18 13:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainMap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traindata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='traindata',
            name='lattitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='traindata',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='traindata',
            name='speed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='traindata',
            name='train_id',
            field=models.CharField(max_length=100),
        ),
    ]
